const fs = require('fs');
let content = fs.readFileSync('src/data/panderetaData.js', 'utf8');

const newRitmosV2 = `export const RITMOS_V2 = [
  // ─────────────────────────────────────────────────────────────
  // MUIÑEIRA (6/8)
  // Base que tú definiste: ti-ti-co
  // ─────────────────────────────────────────────────────────────
  {
    id: 'muineira-base',
    genero: 'Muiñeira',
    nombre: 'Muiñeira · Base',
    compas: '6/8',
    patron: 'ti - ti - co | ti - ti - co',
    patron_array: ['ti', 'ti', 'co', 'ti', 'ti', 'co'],
    variant_of: null,
    tags: ['base'],
    dificultad: 'Básica',
    region: 'Galicia',
    descripcion: 'Célula base: ti-ti-co (repetición continua en 6/8).',
  },
  {
    id: 'muineira-vella-tumm',
    genero: 'Muiñeira',
    nombre: 'Muiñeira · Vella (con tumm)',
    compas: '6/8',
    patron: 'tumm - ti - co | tumm - ti - co',
    patron_array: ['tumm', 'ti', 'co', 'tumm', 'ti', 'co'],
    variant_of: 'muineira-base',
    tags: ['vella', 'tumm'],
    dificultad: 'Intermedia',
    region: 'Galicia',
    descripcion: 'Variante vella: arranque con golpe grave/sordo (tumm).',
  },
  {
    id: 'muineira-con-trr',
    genero: 'Muiñeira',
    nombre: 'Muiñeira · Con riscado (trr)',
    compas: '6/8',
    patron: 'ti - trr - co | ti - trr - co',
    patron_array: ['ti', 'trr', 'co', 'ti', 'trr', 'co'],
    variant_of: 'muineira-base',
    tags: ['trr'],
    dificultad: 'Intermedia',
    region: 'Galicia',
    descripcion: 'Riscado ornamental (trr), idealmente cerrado con co.',
  },
  {
    id: 'muineira-mixta',
    genero: 'Muiñeira',
    nombre: 'Muiñeira · Mixta (tumm + trr)',
    compas: '6/8',
    patron: 'tumm - trr - co | tumm - trr - co',
    patron_array: ['tumm', 'trr', 'co', 'tumm', 'trr', 'co'],
    variant_of: 'muineira-base',
    tags: ['tumm', 'trr', 'mixta'],
    dificultad: 'Avanzada',
    region: 'Galicia',
    descripcion: 'Mixta: grave + riscado (trr) con cierre co.',
  },
  {
    id: 'muineira-longa',
    genero: 'Muiñeira',
    nombre: 'Muiñeira · Longa (doble célula)',
    compas: '6/8',
    patron: 'ti - ti - co - ti - ti - co',
    patron_array: ['ti', 'ti', 'co', 'ti', 'ti', 'co'],
    variant_of: 'muineira-base',
    tags: ['longa'],
    dificultad: 'Básica',
    region: 'Galicia',
    descripcion: 'Mis mismos golpes base, pero presentado como frase continua (útil para editor).',
  },

  // ─────────────────────────────────────────────────────────────
  // JOTA (3/4 o 6/8 según escuela)
  // Base que tú definiste: ti-co-ti-co-ti-co-ti
  // ─────────────────────────────────────────────────────────────
  {
    id: 'jota-base',
    genero: 'Jota',
    nombre: 'Jota · Base',
    compas: '3/4 (o 6/8)',
    patron: 'ti - co - ti - co - ti - co - ti',
    patron_array: ['ti', 'co', 'ti', 'co', 'ti', 'co', 'ti'],
    variant_of: null,
    tags: ['base'],
    dificultad: 'Básica',
    region: 'Galicia',
    descripcion: 'Alternancia larga típica que tú usas como base.',
  },
  {
    id: 'jota-con-tumm',
    genero: 'Jota',
    nombre: 'Jota · Con tumm (arranque grave)',
    compas: '3/4 (o 6/8)',
    patron: 'tumm - co - ti - co - ti - co - ti',
    patron_array: ['tumm', 'co', 'ti', 'co', 'ti', 'co', 'ti'],
    variant_of: 'jota-base',
    tags: ['tumm'],
    dificultad: 'Intermedia',
    region: 'Galicia',
    descripcion: 'Arranque con grave/sordo para marcar el pulso fuerte.',
  },
  {
    id: 'jota-con-trr',
    genero: 'Jota',
    nombre: 'Jota · Con riscado (trr)',
    compas: '3/4 (o 6/8)',
    patron: 'ti - trr - co - ti - co - ti - co',
    patron_array: ['ti', 'trr', 'co', 'ti', 'co', 'ti', 'co'],
    variant_of: 'jota-base',
    tags: ['trr'],
    dificultad: 'Intermedia',
    region: 'Galicia',
    descripcion: 'Riscado insertado y cerrado con co.',
  },
  {
    id: 'jota-mixta',
    genero: 'Jota',
    nombre: 'Jota · Mixta (tumm + trr)',
    compas: '3/4 (o 6/8)',
    patron: 'tumm - trr - co - ti - co - ti - co',
    patron_array: ['tumm', 'trr', 'co', 'ti', 'co', 'ti', 'co'],
    variant_of: 'jota-base',
    tags: ['tumm', 'trr', 'mixta'],
    dificultad: 'Avanzada',
    region: 'Galicia',
    descripcion: 'Grave + riscado con cierre co, resto alternancia.',
  },
  {
    id: 'jota-curta',
    genero: 'Jota',
    nombre: 'Jota · Curta (plantilla corta)',
    compas: '3/4 (o 6/8)',
    patron: 'ti - co - ti - co',
    patron_array: ['ti', 'co', 'ti', 'co'],
    variant_of: 'jota-base',
    tags: ['curta'],
    dificultad: 'Básica',
    region: 'Galicia',
    descripcion: 'Plantilla corta para practicar alternancia y asignarla a canciones simples.',
  },

  // ─────────────────────────────────────────────────────────────
  // PASODOBLE (2/4)
  // ─────────────────────────────────────────────────────────────
  {
    id: 'pasodoble-base',
    genero: 'Pasodoble',
    nombre: 'Pasodoble · Base',
    compas: '2/4',
    patron: 'ti - co | ti - co',
    patron_array: ['ti', 'co', 'ti', 'co'],
    variant_of: null,
    tags: ['base'],
    dificultad: 'Básica',
    region: 'Galicia',
    descripcion: 'Binario cuadrado (mínimo viable para pasodoble).',
  },
  {
    id: 'pasodoble-con-tumm',
    genero: 'Pasodoble',
    nombre: 'Pasodoble · Con tumm (marcado)',
    compas: '2/4',
    patron: 'tumm - co | tumm - co',
    patron_array: ['tumm', 'co', 'tumm', 'co'],
    variant_of: 'pasodoble-base',
    tags: ['tumm'],
    dificultad: 'Intermedia',
    region: 'Galicia',
    descripcion: 'Marcado grave en los tiempos fuertes.',
  },
  {
    id: 'pasodoble-con-trr',
    genero: 'Pasodoble',
    nombre: 'Pasodoble · Con riscado (trr)',
    compas: '2/4',
    patron: 'ti - trr - co - ti',
    patron_array: ['ti', 'trr', 'co', 'ti'],
    variant_of: 'pasodoble-base',
    tags: ['trr'],
    dificultad: 'Intermedia',
    region: 'Galicia',
    descripcion: 'Riscado insertado y cerrado con co dentro del compás.',
  },
  {
    id: 'pasodoble-mixta',
    genero: 'Pasodoble',
    nombre: 'Pasodoble · Mixta (tumm + trr)',
    compas: '2/4',
    patron: 'tumm - trr - co - tumm',
    patron_array: ['tumm', 'trr', 'co', 'tumm'],
    variant_of: 'pasodoble-base',
    tags: ['tumm', 'trr', 'mixta'],
    dificultad: 'Avanzada',
    region: 'Galicia',
    descripcion: 'Grave + riscado con cierre co, remate en grave.',
  },
  {
    id: 'pasodoble-longo',
    genero: 'Pasodoble',
    nombre: 'Pasodoble · Longo (doble compás)',
    compas: '2/4',
    patron: 'ti - co - ti - co - ti - co - ti - co',
    patron_array: ['ti', 'co', 'ti', 'co', 'ti', 'co', 'ti', 'co'],
    variant_of: 'pasodoble-base',
    tags: ['longo'],
    dificultad: 'Básica',
    region: 'Galicia',
    descripcion: 'Extensión para práctica continua y editor.',
  },

  // ─────────────────────────────────────────────────────────────
  // RUMBA (4/4)
  // ─────────────────────────────────────────────────────────────
  {
    id: 'rumba-base',
    genero: 'Rumba',
    nombre: 'Rumba · Base',
    compas: '4/4',
    patron: 'ti - co - ti - co',
    patron_array: ['ti', 'co', 'ti', 'co'],
    variant_of: null,
    tags: ['base'],
    dificultad: 'Básica',
    region: 'Galicia',
    descripcion: 'Base simétrica en 4/4.',
  },
  {
    id: 'rumba-con-tumm',
    genero: 'Rumba',
    nombre: 'Rumba · Con tumm (pulso fuerte)',
    compas: '4/4',
    patron: 'tumm - co - ti - co',
    patron_array: ['tumm', 'co', 'ti', 'co'],
    variant_of: 'rumba-base',
    tags: ['tumm'],
    dificultad: 'Intermedia',
    region: 'Galicia',
    descripcion: 'Marca el primer pulso con grave/sordo.',
  },
  {
    id: 'rumba-con-trr',
    genero: 'Rumba',
    nombre: 'Rumba · Con riscado (trr)',
    compas: '4/4',
    patron: 'ti - trr - co - ti',
    patron_array: ['ti', 'trr', 'co', 'ti'],
    variant_of: 'rumba-base',
    tags: ['trr'],
    dificultad: 'Intermedia',
    region: 'Galicia',
    descripcion: 'Riscado insertado y cerrado con co.',
  },
  {
    id: 'rumba-mixta',
    genero: 'Rumba',
    nombre: 'Rumba · Mixta (tumm + trr)',
    compas: '4/4',
    patron: 'tumm - trr - co - ti',
    patron_array: ['tumm', 'trr', 'co', 'ti'],
    variant_of: 'rumba-base',
    tags: ['tumm', 'trr', 'mixta'],
    dificultad: 'Avanzada',
    region: 'Galicia',
    descripcion: 'Grave + riscado con cierre co, continúa con ti.',
  },
  {
    id: 'rumba-longa',
    genero: 'Rumba',
    nombre: 'Rumba · Longa (8 golpes)',
    compas: '4/4',
    patron: 'ti - co - ti - co | ti - co - ti - co',
    patron_array: ['ti', 'co', 'ti', 'co', 'ti', 'co', 'ti', 'co'],
    variant_of: 'rumba-base',
    tags: ['longa'],
    dificultad: 'Básica',
    region: 'Galicia',
    descripcion: 'Extensión para frase completa.',
  },

  // ─────────────────────────────────────────────────────────────
  // MANEO (variable; en tu app lo dejamos como plantilla)
  // ─────────────────────────────────────────────────────────────
  {
    id: 'maneo-base',
    genero: 'Maneo',
    nombre: 'Maneo · Base',
    compas: '6/8 (frecuente) / variable',
    patron: 'ti - co - ti - co',
    patron_array: ['ti', 'co', 'ti', 'co'],
    variant_of: null,
    tags: ['base'],
    dificultad: 'Intermedia',
    region: 'Galicia',
    descripcion: 'Plantilla base para alternancia rápida con rotación continua.',
  },
  {
    id: 'maneo-con-tumm',
    genero: 'Maneo',
    nombre: 'Maneo · Con tumm',
    compas: '6/8 (frecuente) / variable',
    patron: 'tumm - co - ti - co',
    patron_array: ['tumm', 'co', 'ti', 'co'],
    variant_of: 'maneo-base',
    tags: ['tumm'],
    dificultad: 'Intermedia',
    region: 'Galicia',
    descripcion: 'Arranque marcado con grave.',
  },
  {
    id: 'maneo-con-trr',
    genero: 'Maneo',
    nombre: 'Maneo · Con trr',
    compas: '6/8 (frecuente) / variable',
    patron: 'ti - trr - co - ti',
    patron_array: ['ti', 'trr', 'co', 'ti'],
    variant_of: 'maneo-base',
    tags: ['trr'],
    dificultad: 'Intermedia',
    region: 'Galicia',
    descripcion: 'Riscado ornamental y cierre con co.',
  },
  {
    id: 'maneo-mixta',
    genero: 'Maneo',
    nombre: 'Maneo · Mixta (tumm + trr)',
    compas: '6/8 (frecuente) / variable',
    patron: 'tumm - trr - co - ti',
    patron_array: ['tumm', 'trr', 'co', 'ti'],
    variant_of: 'maneo-base',
    tags: ['tumm', 'trr', 'mixta'],
    dificultad: 'Avanzada',
    region: 'Galicia',
    descripcion: 'Grave + riscado, cierre co.',
  },
  {
    id: 'maneo-longo',
    genero: 'Maneo',
    nombre: 'Maneo · Longo (6 golpes)',
    compas: '6/8 (frecuente) / variable',
    patron: 'ti - co - ti - co - ti - co',
    patron_array: ['ti', 'co', 'ti', 'co', 'ti', 'co'],
    variant_of: 'maneo-base',
    tags: ['longo'],
    dificultad: 'Intermedia',
    region: 'Galicia',
    descripcion: 'Extensión continua para práctica y editor.',
  },

  // ─────────────────────────────────────────────────────────────
  // ALALÁ (LIBRE) — por definición sin patrón fijo
  // Aquí las “variantes” son SOLO plantillas de acompañamiento opcional
  // ─────────────────────────────────────────────────────────────
  {
    id: 'alala-libre',
    genero: 'Alalá',
    nombre: 'Alalá · Libre',
    compas: 'Libre',
    patron: '(libre)',
    patron_array: [],
    variant_of: null,
    tags: ['base', 'libre'],
    dificultad: 'Avanzada',
    region: 'Galicia',
    descripcion: 'Alalá: canto libre. La app debe permitir anotación sin patrón fijo.',
  },
  {
    id: 'alala-marcado-ti',
    genero: 'Alalá',
    nombre: 'Alalá · Acompañamiento (ti suelto)',
    compas: 'Libre',
    patron: 'ti … (eventos sueltos)',
    patron_array: ['ti'],
    variant_of: 'alala-libre',
    tags: ['plantilla'],
    dificultad: 'Intermedia',
    region: 'Galicia',
    descripcion: 'Plantilla mínima: un ti suelto para marcar entradas (no patrón fijo).',
  },
  {
    id: 'alala-ti-co',
    genero: 'Alalá',
    nombre: 'Alalá · Acompañamiento (ti - co)',
    compas: 'Libre',
    patron: 'ti - co … (eventos sueltos)',
    patron_array: ['ti', 'co'],
    variant_of: 'alala-libre',
    tags: ['plantilla'],
    dificultad: 'Intermedia',
    region: 'Galicia',
    descripcion: 'Plantilla suave: alternancia mínima sin imponer métrica.',
  },
  {
    id: 'alala-con-tumm',
    genero: 'Alalá',
    nombre: 'Alalá · Acompañamiento (tumm puntual)',
    compas: 'Libre',
    patron: 'tumm … (puntos de apoyo)',
    patron_array: ['tumm'],
    variant_of: 'alala-libre',
    tags: ['plantilla', 'tumm'],
    dificultad: 'Intermedia',
    region: 'Galicia',
    descripcion: 'Uso puntual del grave/sordo como apoyo expresivo.',
  },
  {
    id: 'alala-con-trr',
    genero: 'Alalá',
    nombre: 'Alalá · Acompañamiento (trr puntual)',
    compas: 'Libre',
    patron: 'trr - co … (ornamento)',
    patron_array: ['trr', 'co'],
    variant_of: 'alala-libre',
    tags: ['plantilla', 'trr'],
    dificultad: 'Avanzada',
    region: 'Galicia',
    descripcion: 'Ornamento puntual con cierre co (si usas trr).',
  }
];`;

content = content.replace(/export const RITMOS_V2 = \[[\s\S]*?\];/m, newRitmosV2);

fs.writeFileSync('src/data/panderetaData.js', content, 'utf8');
console.log('Done replacing RITMOS_V2');
